spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: false

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG

app:
  domain: http://localhost:8080