name: Snyk Security Scan

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  snyk:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4.7.0
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Install Snyk CLI
        uses: snyk/actions/setup@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Snyk Code (SAST) 분석
        run: |
          snyk code test --sarif > snyk-code.sarif || echo '{}' > snyk-code.sarif

      - name: Snyk Open Source (SCA) 분석
        run: snyk test --all-projects || true

      - name: Snyk IaC 분석
        run: snyk iac test --report || true

      - name: SARIF 결과 GitHub에 업로드
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-code.sarif